### ISSUE TITLE
Ensure all languages are set up in C3P0 / Share

### ISSUE THREAD

**Issue by ZakGhouze** [Vorski-Imagineering/share#103]
Need to ensure Turkish, French, German, Italian, Dutch, Polish, Japanese & Russian are set up as languages in C3P0 and Share...

**Comment by ZakGhouze** [comment]
(As per translation manual -:
- add item to languages array in shareApp/app/scripts/controllers/main.js file
- add new file in shareApp/app/i18n directory in schema lang_en_EN.js
- add item in Gruntfile.js in section i18nextract in array default_options.lang
- execute make makemessages in main directory)

**Comment by vvorski** [comment]
@ZakGhouze are you working on this? It was assigned to @konewa without a comment.

**Comment by vvorski** [comment]
https://app.asana.com/0/10716696677070/10802319169818
