### ISSUE TITLE
Possible solution / format / template for InfoSite

### ISSUE THREAD

**Issue by ZakGhouze** [Vorski-Imagineering/share#105]
Zak to investigate potential templates etc. for InfoSite

**Comment by ZakGhouze** [comment]
Looking at WordPress / using Dreamweaver to make a nice design / frontend...

**Comment by vvorski** [comment]
http://themeforest.net/

is great for wp themes

**Comment by vvorski** [comment]
move task to asana: https://app.asana.com/0/10716696677062/10716696677104
