### ISSUE TITLE
CSS change on new version

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#106]
by @rafallo  "CSS is cached via HTML5 application cache. According to HTML5 Application Cache spec cache should be updated during user first visit after manifest file change. So, after cache update you should reload page and changes should be visible.

I've add event listener which notify user that cache has been updated and you can reload page right now. But there is one huge "no" for it: to make offline mode work, Share is caching friends profile images and share images in HTML5 app cache, so when you add new new share with image, application will ask you for reloading next time. 
I will check if I can cache images not in app cache, but local storage."

**Comment by vvorski** [comment]
This was mentioned in another bug. So I want to know how it will work when we upgrade the app for new version or bugs fixed? We cannot expect normal users to dump their browser cache to upgrade the app...

**Comment by konewa** [comment]
@rafallo any ideas ?

**Comment by rafallo** [comment]
HTML5 application cache is strictly connected with offline mode in Share. So we could disable app cache (and related bug), but it would broke offline mode also.

**Comment by vvorski** [comment]
@konewa let's discuss, need architect-level decision.

**Comment by vvorski** [comment]
- write problem description on stackexchange
- make sandbox example

**Comment by vvorski** [comment]
- write question on stackexchange on how to implement offline mode with angular

**Comment by rafallo** [comment]
It's really difficult to reproduce that problem. I've introduced a few improvements to manifest file and since that time cache is invalidating in proper way.

**Comment by vvorski** [comment]
Let's hope it's working now...
