### ISSUE TITLE
use-cases for group sharing

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#109]
Let's gather ideas for use-cases for group/circle sharing - then based on these use-cases it should be easier to design both the system and the UI for multi-person sharing.

https://docs.google.com/a/vorski.com/document/d/1k1V0kBoBO1poq9eAAN04Fq4RYcV5tBN072FQ2wPv9nI/edit#heading=h.6c91o9ieqdsg

**Comment by vvorski** [comment]
@ZakGhouze can you please put in the group-sharing model use-cases you have into the above document?

**Comment by ZakGhouze** [comment]
Will do...

**Comment by vvorski** [comment]
@konewa can you give some ideas?!

**Comment by vvorski** [comment]
I wrote-up mine.

**Comment by vvorski** [comment]
@konewa  ok, dokończyłem use-casey z Zakiem.

**Comment by vvorski** [comment]
Reviewed, completed.
