### ISSUE TITLE
Sometimes images do not display

### ISSUE THREAD

**Issue by konewa** [Vorski-Imagineering/share#11]
see the photos
![Uploading IMG_3112.png . . .]()
![Uploading IMG_3111.png . . .]()
![Uploading IMG_3113.png . . .]()

**Comment by rafallo** [comment]
Is it still occuring?

I can't reproduce it.

**Comment by vvorski** [comment]
Yes, every time.

**Comment by rafallo** [comment]
Could you please provide more information?
On my development machine (Chrome) is everything ok. My android phone also shows images.

Is it related to notifications or timeline or upload?
Is it on iPhone or desktop?
Is it offline or online mode?

**Comment by vvorski** [comment]
Ok now I guess, will see if it comes up when we do final test run...
