### ISSUE TITLE
review text shown in facebook when a Share is posted...

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#12]
how much can we customise the text showing in facebook?

review docst here:

https://developers.facebook.com/docs/reference/dialogs/feed/

**Comment by vvorski** [comment]
We have the following to set it seems:
- link - The link attached to this post
- picture - The URL of a picture attached to this post. The picture must be at least 200px by 200px. See our documentation on maximizing distribution for media content for more information on sizes.
- name - The name of the link attachment.
- caption - The caption of the link (appears beneath the link name). If not specified, this field is automatically populated with the URL of the link.
- description - The description of the link (appears beneath the link caption). If not specified, this field is automatically populated by information scraped from the link, typically the title of the page.
- properties - A JSON object of key/value pairs which will appear in the stream attachment beneath the description, with each property on its own line. Keys must be strings, and values can be either strings or JSON objects with the keys text and href.
- actions - A JSON array containing a single object describing the action link which will appear next to the 'Comment' and 'Like' link under posts. The contained object must have the keys name and link.

**Comment by vvorski** [comment]
@rafallo can you please show me where in C3PO translations the above strings are so I can edit them?

**Comment by rafallo** [comment]
I have to add these strings to C3PO and update doc file. I will do it next week.

**Comment by vvorski** [comment]
@rafallo ok, please do.

**Comment by rafallo** [comment]
these keys are "I've just shared you", "You've just shared me" and "click to redirect to share".

**Comment by vvorski** [comment]
@rafallo  please put into the comment field which is which...

https://docs.google.com/a/vorski.com/spreadsheet/ccc?key=0AregDapYXphgdEF5bENCeHlfcjl3YjBER2V6bkFJSWc&usp=drive_web#gid=0

**Comment by rafallo** [comment]
I've just updated that doc.

**Comment by vvorski** [comment]
now understood.
