### ISSUE TITLE
Bugs in google spreadsheet title "HD - testy Share"

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#123]
Should we check if these are all fixed?

https://docs.google.com/a/vorski.com/spreadsheet/ccc?key=0AlC7NiXWvfzUdHJtQTJTem91Um1WeVB0WVlzZGZ1b1E&usp=drive_web#gid=0

**Comment by konewa** [comment]
fixed

**Comment by vvorski** [comment]
confirmed, file deleted.
