### ISSUE TITLE
Users Missing photos...

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#127]
![screen shot 2014-03-12 at 20 16 34](https://f.cloud.github.com/assets/1789426/2402529/506308a0-aa23-11e3-89a1-e48d118fc995.png)

**Comment by vvorski** [comment]
today not reproducible.

**Comment by vvorski** [comment]
not working again... :(

![screen shot 2014-03-17 at 15 48 55](https://f.cloud.github.com/assets/1789426/2437895/bd048472-adeb-11e3-9a39-68f8b4ef2052.png)

**Comment by vvorski** [comment]
At the same time the following happens:

![screen shot 2014-03-17 at 15 53 10](https://f.cloud.github.com/assets/1789426/2437944/58d43da2-adec-11e3-8ed7-5af012e4937f.png)

![screen shot 2014-03-17 at 15 52 58](https://f.cloud.github.com/assets/1789426/2437947/5d389ce4-adec-11e3-8b3f-0d5dc83b0902.png)

**Comment by rafallo** [comment]
crazy bug. I can't reproduce it. I tried on desktop chrome, android chrome, android stock browser...
Same issue is with hidden friend list.

**Comment by vvorski** [comment]
no problem in incognito mode, no problem when I make a new account on computer... no idea then. let's hope it doesn't happen anywhere else...
