### ISSUE TITLE
My comments were deleted from Share app translations by shareapptranslator

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#128]
Why would this happen?

I wrote comments:
![screen shot 2014-03-14 at 18 19 19](https://f.cloud.github.com/assets/1789426/2424296/509056f6-aba5-11e3-8fe4-e55f59a6b0e6.png)

shareapptranslator user deleted them...
![screen shot 2014-03-14 at 18 19 44](https://f.cloud.github.com/assets/1789426/2424297/58a3a60e-aba5-11e3-8baa-7f4eccae2797.png)

**Comment by konewa** [comment]
Where is it used ? _ I will add this comments

**Comment by vvorski** [comment]
let's hope it doesn't happen again...
