### ISSUE TITLE
Need protection against double submit

### ISSUE THREAD

**Issue by konewa** [Vorski-Imagineering/share#13]
![Uploading IMG_3115.png . . .]()

**Comment by vvorski** [comment]
@rafallo was this fixed? I looked at the referenced commit but don't see which is the code to deal with double submit.

**Comment by rafallo** [comment]
I've made a mistake and totally mess up it.
It is fixed but not in this referenced commit.  

Proper solution is in 8d25fff in file shareApp/app/views/newShare.html .  
The worst thing is that name of this commit is "cleaning up". 

To be honest, both commits are cleaning up, fix for #13 and friends lazy loading.

**Comment by vvorski** [comment]
This is hard to test so I will assume it is done! :)
