### ISSUE TITLE
Wżucic ikonkę serduszko Share do google docs

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#130]
![screen shot 2014-03-21 at 15 11 49](https://f.cloud.github.com/assets/1789426/2484272/2b23e1ba-b10b-11e3-96bc-873de058e992.png)

wstawić tu proszę:

https://drive.google.com/a/vorski.com/?urp=https://docs.google.com/&pli=1#folders/0B5YY6TvvjQRieDNWUFpkbXRjakk

**Comment by rimbambala** [comment]
Done
