### ISSUE TITLE
code review: main.js notifications.js

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#142]
https://github.com/ShareApp/share/blob/master/cloudCode/cloud/main.js
https://github.com/ShareApp/share/blob/master/cloudCode/cloud/notifications.js
I think all require should be at top of file.
All variables wrote with camelCases style, but 'userquery' is not.

Need more comments describing code

from @l80

**Comment by rafallo** [comment]
fixed

**Comment by vvorski** [comment]
looks good.
