### ISSUE TITLE
code review: app.js

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#144]
https://github.com/ShareApp/share/blob/master/cloudCode/cloud/app.js
{12}
- Express application which can be launched only in Parse.com cloud.
  What is that mean? Do your app can be running without parse.com? If yes than you should include Express framework to documentation as required component. http://expressjs.com/
  files.push("https://graph.facebook.com/" + item.get('fromUser').get('facebookid') + "/picture?width=65&height=65");
    files.push("https://graph.facebook.com/" + item.get('toUser').get('facebookid') + "/picture?width=65&height=65");
  Maybe better to move "https://graph.facebook.com/" to settings?
  Need more comments.

**Comment by rafallo** [comment]
I've added more comments. By the way, I've added additional comments to shareApp/app/scripts/app.js file.

**Comment by vvorski** [comment]
looks good.
