### ISSUE TITLE
code review: karma.conf.js

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#145]
https://github.com/ShareApp/share/blob/master/shareApp/karma.conf.js
What is it? Testing tool? How about add it to README.md? And where is info how to run tests?

**Comment by rafallo** [comment]
There is no working tests, so we have to options:
- develop some tests (but due to fragile layout it may be not a good idea),
- abandon testing during development process and delete karma.conf.js file at all.

**Comment by vvorski** [comment]
@rafallo Well if it's not set-up at all let's delete it from here and the dependencies, we will add it again if/when we add tests.

**Comment by vvorski** [comment]
test removed.
