### ISSUE TITLE
Move share said icon before date?

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#151]
![screen shot 2014-03-25 at 22 45 47](https://f.cloud.github.com/assets/1789426/2519262/42aba3ba-b46f-11e3-9865-1569d12e8121.png)
- move the message icon before the time. what do you think?
- also move the share-type icon a bit higher? mid-way of the top line.

**Comment by rimbambala** [comment]
@vvorski What is this message icon used for?

**Comment by vvorski** [comment]
@rimbambala  how long ago the Share❣ was created.

**Comment by rimbambala** [comment]
![share-06d](https://cloud.githubusercontent.com/assets/6513797/2568765/e68a560a-b8e5-11e3-8e36-af60371c3140.jpg)

**Comment by vvorski** [comment]
Same as #51
