### ISSUE TITLE
angular.js <-> parse.com integration technical documentation

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#153]
Need overview technical documentation on angular.js <-> parse.com integration technical documentation, at level of:

https://github.com/ShareApp/share/wiki/Offline-mode

**Comment by rafallo** [comment]
Take a look: https://github.com/ShareApp/share/wiki/Integration-Parse.com-with-Angular.js
Is it sufficient? Is there enough information?

I think about this wiki page as a bank of links rather than self-explainatory page.

**Comment by vvorski** [comment]
updated, ok for now.
