### ISSUE TITLE
bower install gives error: Unable to find a suitable version for angular

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#157]
Unable to find a suitable version for angular, please choose one:
    1) angular#1.0.7 which resolved to 1.0.7 and is required by angular-cookies#1.0.7, angular-mocks#1.0.7, angular-resource#1.0.7, angular-sanitize#1.0.7, angular-scenario#1.0.7, angular-translate#0.9.4, angular-translate-handler-log#0.1.2, angular-translate-loader-static-files#0.1.2, angular-translate-storage-local#0.1.2 
    2) angular#1.0.8 which resolved to 1.0.8 and is required by angular-cookies#1.0.8, angular-translate#1.1.0, angular-translate#1.1.1, angular-translate-storage-cookie#0.1.8 
    3) angular#1.2.0 which resolved to 1.2.0 and is required by angular-touch#1.2.0 
    4) angular#1.2.15 which resolved to 1.2.15 and is required by share 
    5) angular#>= 1.0.6 which resolved to 1.2.15 and is required by angular-ui-router#0.2.0

**Comment by rafallo** [comment]
fixed. Please, check if it works.

**Comment by vvorski** [comment]
Looks good
