### ISSUE TITLE
My Share view - needs menu button?

### ISSUE THREAD

**Issue by ZakGhouze** [Vorski-Imagineering/share#161]
See a timeline of all my Share❣s

Display a time line similar to path or instagram showing the photos of the shares and their information - displayed when you click on your own icon... BUT SHOULD THIS BE A MENU OPTION? (Rather than HOME, we have MAIN and MINE or somesuch?)

I had no idea from initial use of app that clicking on my own icon would bring up a list of my Shares! It is not obvious, so maybe needs to be mentioned in docs or added explicitly as a menu option.

**Comment by ZakGhouze** [comment]
Also should my name be a link to my own FB page?

**Comment by vvorski** [comment]
@ZakGhouze  added the link to FB page to #70

**Comment by vvorski** [comment]
Adding to menu is #84

**Comment by ZakGhouze** [comment]
Closing - as confirmed this is handled in issue #84
