### ISSUE TITLE
re-direct for shareItem

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#167]
When we move application to own server, regarding the re-direct, why don't we map /shareItem/ to the application in javascript and handle the URL re-write in Javascript?

Otherwise use PHP re-direct in that directory?

from: 
http://www.geekboards.com/forums/showthread.php?t=755

<?php
header("HTTP/1.1 301 Moved Permanently");
header("Location: /#");
?>

**Comment by rafallo** [comment]
On vorski.com there is a redirection made by .htaccess file. It cannot be done via JS because this request never reach index.html file (and related JS)

**Comment by vvorski** [comment]
great. so it's done?!

Victor Vorski
victor@vorski.com　skype:vvorski

**Comment by rafallo** [comment]
Yes.

**Comment by vvorski** [comment]
great!
