### ISSUE TITLE
UI experiment: in list display show the writing over photo

### ISSUE THREAD

**Issue by konewa** [Vorski-Imagineering/share#24]
How about if we showed the writing above the photo, maybe with a lightly opaque background? might look better?

then when we add FB comment display, etc. we can add those like this text below. It will give more space for the photos.

**Comment by rafallo** [comment]
Design?

**Comment by rimbambala** [comment]
A sketch of the experimental design
![share-07-share-view-c3](https://f.cloud.github.com/assets/6513797/2010356/9ea8a422-876c-11e3-8165-667c588c6761.jpg)

**Comment by vvorski** [comment]
@konewa  It looks good, let's experiment a little more. Zdjęcie zrobił bym teraz pełnej długości (teraz obcinamy) a pod tekstem dodał bym pole z opacity aby się trochę odcinało.

**Comment by vvorski** [comment]
- do przemyślenia jak by to wyglądało na zdjęciach w różnych proporcjach.

**Comment by vvorski** [comment]
@rimbambala when we implement #150 so remove the auto generated text many of the Share❣s will have no text or short text so it should look better.

**Comment by ZakGhouze** [comment]
Looks OK superimposed on pic... Especially as we are losing surrounding text (i.e. this example would just say Café Racer)

This would also shrink screenspace taken up and improve general look and flow of timelines...

**Comment by vvorski** [comment]
Let's leave this for now, let people play with Share a bit and see what feedback comes back...
