### ISSUE TITLE
Share❣ notification

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#26]
User stories:
18  Facebook Message Notification       As a user I want to     Confirmation message to other party on Share!   When a Share! is created a confirmation request asking the other party to confirm the Share! is sent via Facebook
19  Facebook Message Notification       As a user I want to     Confirmation message to other party on Share! return    When one side of the Share! markes a Share! as returned a confirmation request for this is sent via FB message to other party in the Share!

Options review from HD:
https://docs.google.com/a/vorski.com/document/d/1BcpETJ8oYoyHR8xbafUuwQqMcbjwfQygR0Vcnsz1fz0/edit

**Comment by vvorski** [comment]
@konewa I read this but I don't understand many points, and I am not clear what your recommendation is as to what we should do.

Let's do a meeting with technical team to review.

**Comment by vvorski** [comment]
@rafallo  let's review once again and do estimate.

**Comment by rafallo** [comment]
I've reviewed this and there are only two updates.

**Comment by vvorski** [comment]
@konewa  can you please give me a recommendation from your side as to what the main options are and the plusses and minuses of each? From a usability and realistic implementation point of view what do you recommend?

**Comment by vvorski** [comment]
@konewa  przedyskutujmy jeszcze raz na następnym spotkaniu

**Comment by rafallo** [comment]
@vvorski, there are two ways to put notification to user which, I think, fits to Share
via Chat API
- it allows to send direct message
- gives message notification in Facebook top bar, which puts Share on high level of trust (or irritation if lots of messages),
- needs much work
- will make application heavier than now
- probably do not need to confirmation from user
- not tested by us

posting on timeline 
- it is done right now
- it gives only Facebook notification on top bar
- is publicly visible (or only for friends)
- can post on user friend's timeline or user timeline
- need user confirmation
- cannot programmatically fill text box with placeholder

**Comment by konewa** [comment]
@rafallo could you make estimation for notification via Chat API?

**Comment by konewa** [comment]
@vvorskiI think that we have to move this issue from 0.5 acceptance criteria - it's not a bug but changes in functionality

**Comment by vvorski** [comment]
@konewa it is user story 18 & 19 above, no?

**Comment by vvorski** [comment]
After much discussion decided to leave as is until 1.0

When we will make a phone-gap application we will have real push notifications which handle this better.
