### ISSUE TITLE
Re-think create Share❣ create menu...

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#30]
Currently the buttons are displayed over the text below so hard to read, we should put in a semi-transparent background to improve usability

![screen shot 2013-11-01 at 12 22 37](https://f.cloud.github.com/assets/1789426/1645867/ae21212a-590b-11e3-9687-1711a49e8ed3.png)

**Comment by konewa** [comment]
Design konieczny + tekst thing time promise

**Comment by rimbambala** [comment]
In the very first design icons had shadow beneath them which made them more distinctive. I consider adding a semi-transparent background not a good idea. I think it wouldn't look good. In the attachment you can find a preview.
![share-07_sharebuttons](https://f.cloud.github.com/assets/6513797/2010277/ab2fb182-876b-11e3-8178-c2155e51b1b6.jpg)

**Comment by vvorski** [comment]
@konewa where is the text? Also do you think this is enough? I was thinking of a 1/4 circle centered at the corner under all the items ... Do you understand what I mean?

**Comment by vvorski** [comment]
![](http://www.code4app.com/photo/51addcca6803fab86b000000_1.png)

**Comment by konewa** [comment]
@rimbambala  take a look:
![](http://www.piccante.co/images/bubble.png)
![](http://freebiesbug.com/wp-content/uploads/2012/10/Circular_navigation_bar_free_psd.jpg)

**Comment by vvorski** [comment]
![screen shot 2013-12-01 at 22 16 02](https://f.cloud.github.com/assets/1789426/1651414/5ca6b0d6-5ad6-11e3-9e61-2dc90a66dff7.png)

**Comment by vvorski** [comment]
need design.

**Comment by konewa** [comment]
@rimbambala we have to talk about this

**Comment by rimbambala** [comment]
![share-addshare-01](https://cloud.githubusercontent.com/assets/6513797/2578490/8562c360-b991-11e3-83e5-274c382be10d.jpg)
Design update built on the basis of our discussion.

**Comment by vvorski** [comment]
@rimbambala ok, looks good, discussed with zak, let's try putting Share logo above each icon - yes it will be three times on the page but for user understanding that's useful, as well as for branding.

**Comment by ZakGhouze** [comment]
3 column idea is good... Clear and utilises white space..

Also use visual cues, and confirmations. Once we've selected time or thing or promise, things should reflect that... e.g. Enter details of TIME SHARE here, Enter details of PROMISE here, etc. Given that people can go back one page fairly easily, this will help things...

**Comment by vvorski** [comment]
I just had a thought. On this screen why don't we display SIX buttons:
- lend thing
- borrow thing
- give time
- receive time
- declare promise
- receive promise

That way we will take care of setting the direction right here...

**Comment by vvorski** [comment]
Having all the six options will also make the whole application easier to understand with that one screen I think... How about it?

**Comment by rimbambala** [comment]
It's ok for me, but before I start working on this issue I need to have the info clarified:
- do we put share logo 6 timeS?
- what about the icons? we have only three not six
- do we resign from using direction chooser on create share screen?
- where should I put "Enter details of TIME SHARE here"? which screen?
- what exact visual cues and confirmation do you mean?

**Comment by vvorski** [comment]
- logo - with six buttons don't need it
- icons: see below
- share create screen remains as we've made it
- "enter details..." - that's the create screen, sorry comment should have been made there
- @ZakGhouze "what exact visual cues and confirmation do you mean?" - comments?

my idea was along these lines... but needs better design!

![8562c360-b991-11e3-83e5-274c382be10d](https://cloud.githubusercontent.com/assets/1789426/2593251/201a7fa0-ba7e-11e3-92d9-11678893c315.jpg)

**Comment by rimbambala** [comment]
![share-addshare-02](https://cloud.githubusercontent.com/assets/6513797/2601247/ce97b988-bb0c-11e3-82f3-96e6b4e627a9.jpg)

**Comment by ZakGhouze** [comment]
The interface should reflect options / thought process, and guide the user?

SO we have choices - 
  first, what type of share? (Thing, Promise, Time);
  second, in which direction? (from me to another, or from another to me i.e. give or receive).

Could we just have the user on the left, then a selectable option (cycling icon, or our three standard icons, which we can highlight or emphasise when selected)... Followed by a simple swipe for direction arrow?

**Comment by vvorski** [comment]
How about the following, also make the the button text the colour of the icon.

![20140405_164518](https://cloud.githubusercontent.com/assets/1789426/2623149/1bf3eec4-bcdc-11e3-9c25-d09f229ed434.jpg)

**Comment by rimbambala** [comment]
![share-addshare-03](https://cloud.githubusercontent.com/assets/6513797/2642215/42c7ee30-bf05-11e3-974a-10f5b3ff9e5e.jpg)

**Comment by vvorski** [comment]
@rimbambala  Looks very good, but as zak pointed out on facebook the button L&F does not match other screens. How can we make these buttons look more like the other screen buttons?

**Comment by rimbambala** [comment]
In my opinion the consistency isn't broken here. Firstly designed button were in the same style everywhere. But there was a decision to change the style and font on the buttons in "create share step" which I was against. #65

**Comment by rimbambala** [comment]
![share-addshare-04](https://cloud.githubusercontent.com/assets/6513797/2667113/31254222-c0a9-11e3-81a8-37b9eb15df9a.jpg)

**Comment by vvorski** [comment]
Some ideas:

![share-addshare-sample 1](https://cloud.githubusercontent.com/assets/1789426/2710937/c17f8270-c4c7-11e3-85ee-9dd19d2e6bfe.jpg)
![share-addshare-sample 2](https://cloud.githubusercontent.com/assets/1789426/2710938/c18f112c-c4c7-11e3-922b-8ce7f8b1597a.jpg)
![share-addshare-sample-3-4](https://cloud.githubusercontent.com/assets/1789426/2710939/c19707a6-c4c7-11e3-937c-6e9f339c3f1e.jpg)
![share-addshare-sample-5-6](https://cloud.githubusercontent.com/assets/1789426/2710940/c1974f68-c4c7-11e3-9d4e-8918a4e053ef.jpg)

**Comment by vvorski** [comment]
@rimbambala  what do you think of the above suggestions?

**Comment by vvorski** [comment]
@rimbambala  pick please whichever of my suggestions you think is best and let's go with that...

**Comment by vvorski** [comment]
Oh, and let's make the edge a bit ragged, I think that will fit better with the other parts of the UI then just a square edge one.

**Comment by rimbambala** [comment]
![share-addshare-05](https://cloud.githubusercontent.com/assets/6513797/2718046/3305518c-c549-11e3-8681-5fefec129a6e.jpg)

**Comment by vvorski** [comment]
ok. let's go with this for now and iterate the design after we get user feedback...

**Comment by vvorski** [comment]
implementing in #172
