### ISSUE TITLE
Android browser share comes up with blank page

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#33]
Was in logged in state, closed browser for a while, came back to share page it comes up blank. After share goes into this mode it stays stuck this way.

Clearing the cache & DB solves the problem.

![screenshot_2013-11-30-14-23-54](https://f.cloud.github.com/assets/1789426/1651171/99837ba6-5ac7-11e3-90b9-eb03b7a5dca8.png)
![screenshot_2013-12-01-20-24-44](https://f.cloud.github.com/assets/1789426/1651173/ab37af7a-5ac7-11e3-9a18-52bbe121e453.png)

**Comment by vvorski** [comment]
@rafallo @konewa this happens every day when I come back to the site (Android 4.0.3, model LG-P700, kernel version 3.0.8-perf+, build number IML74K, software version V10i-AUG-2012, 305Mb ram used, 87Mb free).

it would be nice to fix this at a higher priority.

**Comment by rafallo** [comment]
Temporary fixed, but it needs to pull my changes described in this issue:
https://github.com/angular/angular.js/issues/1356

To see changes you need to delete browser cache.

**Comment by vvorski** [comment]
looks ok.
