### ISSUE TITLE
Re-think Filter Dialog

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#34]
Currently the filter dialog does not fit on the page and is much too big. 
![screenshot_2013-12-01-20-50-40](https://f.cloud.github.com/assets/1789426/1651246/47432770-5acb-11e3-8958-fd6b0155fed8.png)

I propose the following re-arrangement
![search dialog re-imagine-2](https://f.cloud.github.com/assets/1789426/1651232/1a00f04a-5aca-11e3-8c3d-080c89859447.png)

**Comment by rimbambala** [comment]
Simplified and more clear layout for filter dialog.
![share-06c](https://f.cloud.github.com/assets/6513797/2020349/545ab6a6-8831-11e3-8d32-866acdaf753b.jpg)

**Comment by vvorski** [comment]
@konewa  filter contents is ok, but on other screens we are eliminating checkboxes, should we eliminate them on this screen also?

**Comment by vvorski** [comment]
- checkboxes ok.

**Comment by vvorski** [comment]
- needs to be impemented.

**Comment by vvorski** [comment]
@rimbambala  what about empty checkbox? that looks more to what a hand-drawn checkbox would be like - drawing what you have by hand would take a lot of time...

![checkbox-test](https://f.cloud.github.com/assets/1789426/2506496/d0416d22-b3a7-11e3-9f99-66e2b279b17a.jpg)

**Comment by rimbambala** [comment]
![share-06c-filter](https://f.cloud.github.com/assets/6513797/2510408/79f5c86e-b406-11e3-8140-b394fccfc375.jpg)
Update

**Comment by vvorski** [comment]
I think that is better. let's go with this.

**Comment by vvorski** [comment]
Implement in #171
