### ISSUE TITLE
Add languages

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#36]
Please add:
- Russian
- Italian
- Turkish
- Spanish

**Comment by vvorski** [comment]
The design here needs to be changed as this does not look good and won't work when we add more languages

![screen shot 2014-01-19 at 20 05 45](https://f.cloud.github.com/assets/1789426/1949313/e168ece6-80f9-11e3-880f-d9377a05ac4e.png)

**Comment by konewa** [comment]
@vvorski  Lets move this task to 0.5.1

**Comment by vvorski** [comment]
@konewa ok.

**Comment by vvorski** [comment]
documented. see: https://github.com/ShareApp/share/wiki/Share-translations
