### ISSUE TITLE
Make the number display softer

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#38]
Current black looks too strong I think:
![screen shot 2013-11-16 at 05 52 53](https://f.cloud.github.com/assets/1789426/1651257/65514a66-5acc-11e3-9f29-8320509d7ffd.png)

Something more like this would be better (ligher colour and somewhat transparent):
![screen shot 2013-11-16 at 05 52 08](https://f.cloud.github.com/assets/1789426/1651258/79aeac7e-5acc-11e3-9cdc-6606a52fa636.png)

**Comment by konewa** [comment]
Spytać Kamila

**Comment by rimbambala** [comment]
Do we relay need this type of notification in this place? I think it's not informative anyway. We have information about share numbers in the profile.

**Comment by vvorski** [comment]
@rimbambala I think you are right, we eliminated the number from the share, right?

**Comment by konewa** [comment]
@rafallo

**Comment by vvorski** [comment]
currently decided no count for shares. https://drive.google.com/a/vorski.com/#folders/0B01XthWybvS6R2IzNmJuVW9Mbk0
