### ISSUE TITLE
FB-Like a Share❣

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#42]
from time-line and Share❣ details screen want to:
- FB like a Share❣
- see which Share❣s were liked by me (heart in header?) - what options does the FB API give us?

**Comment by konewa** [comment]
see which Share❣s were liked by me - sprawdzić w API RJ

**Comment by vvorski** [comment]
@konewa o tym nie rozmawialiśmy, tu też potrzebny design!!!!

**Comment by vvorski** [comment]
agreed design requirements

**Comment by rimbambala** [comment]
![share-06g](https://cloud.githubusercontent.com/assets/6513797/2642856/37f23c8a-bf10-11e3-8009-681b3eae46fc.jpg)

**Comment by vvorski** [comment]
we should skin it completely - obviously the FB look completely does not work with our UI!

**Comment by rimbambala** [comment]
Pawel Wcislak has to check if styling of facebook likes can by achieved. Frankly, I haven't seen anywhere a styled facebook button.

**Comment by vvorski** [comment]
Since we are an app not just a page I think we can use the Facebook javascript API to do the liking.

http://stackoverflow.com/questions/11218218/trigger-facebook-action-like-with-js-sdk

**Comment by vvorski** [comment]
https://developers.facebook.com/docs/opengraph/guides/og.likes

**Comment by vvorski** [comment]
@rimbambala let's make a design assuming anything is possible

**Comment by rimbambala** [comment]
![share-06h](https://cloud.githubusercontent.com/assets/6513797/2654123/7fefcd8c-bfcd-11e3-896a-ac410d6d4bc1.jpg)

**Comment by rimbambala** [comment]
![share-06i](https://cloud.githubusercontent.com/assets/6513797/2667197/553f69fc-c0aa-11e3-81ce-b31b0132d15a.jpg)

**Comment by vvorski** [comment]
I am thinking at the side like this, getting opinions on facebook.

![share-06i](https://cloud.githubusercontent.com/assets/1789426/2699231/2b111196-c404-11e3-9ec6-c2447c1bc9d6.jpg)

**Comment by vvorski** [comment]
@rimbambala  I think something like the last one would be the best.

**Comment by rimbambala** [comment]
@vvorski Which one do you want me to prepare?

**Comment by vvorski** [comment]
@rimbambala  the third one.

**Comment by rimbambala** [comment]
![share-06j](https://cloud.githubusercontent.com/assets/6513797/2718913/00fe6ce2-c557-11e3-9ff1-43396d9f1be7.jpg)

**Comment by vvorski** [comment]
development in #170
