### ISSUE TITLE
Date on share create should default to now

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#47]
No says dd/mm/yy

![screen shot 2013-12-01 at 23 18 19](https://f.cloud.github.com/assets/1789426/1651522/ef2675ba-5ade-11e3-9173-5ce3108ef2f4.png)

**Comment by vvorski** [comment]
not fixed still:
![screen shot 2013-12-06 at 23 42 28](https://f.cloud.github.com/assets/1789426/1697050/682df4a2-5ed0-11e3-8fa1-3ff044e918b1.png)

**Comment by rafallo** [comment]
Is it on Safari?
Please, refresh your browser cache. 

I've tested it on Android stock browser, Chrome and Safari.
