### ISSUE TITLE
comments for same share displaying differently for different users...

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#53]
Sometimes shows the comments for a completely different Share!
This is how:
http://share-test.parseapp.com/#/sharedItem/9Rsncma47J

looks to three different users...

![screen shot 2013-12-01 at 23 52 00](https://f.cloud.github.com/assets/1789426/1651597/578924cc-5ae4-11e3-9fa8-9b8626c05f37.png)
![screen shot 2013-12-01 at 23 52 33](https://f.cloud.github.com/assets/1789426/1651598/59da47c4-5ae4-11e3-91e6-0775c329652b.png)
![screen shot 2013-12-01 at 23 52 16](https://f.cloud.github.com/assets/1789426/1651600/5befe46a-5ae4-11e3-9195-409f92308667.png)

**Comment by vvorski** [comment]
@konewa gdzie to stoi?

**Comment by rafallo** [comment]
http://share-test.parseapp.com/

**Comment by vvorski** [comment]
ok now I hope.
