### ISSUE TITLE
One user reports seeing people who they have no shares with in their friends list

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#63]
Refreshing the screen seems to have fixed this but it is strange that it appeared.

![screen shot 2013-12-01 at 23 54 57](https://f.cloud.github.com/assets/1789426/1652845/cee7a280-5b22-11e3-92eb-bbfb518049d5.png)

**Comment by konewa** [comment]
Próbujemy reprodukować bug

**Comment by konewa** [comment]
fixed

**Comment by vvorski** [comment]
ok. let's hope it's ok.
