### ISSUE TITLE
Make info site plan

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#90]
Make a google doc to plan the info site
https://docs.google.com/a/vorski.com/document/d/1QCtz15vgcx5athAhTvwwmhx6kCzoqicPsHJp5JTl2gk/edit#
- [x] write down goals
  - different goals depending on phase of project
- [x] site map
- [ ] per page 
  - page goal
  - point form page contents

Note: the site is different from an "app" site in that we are an open community so eventually things like how we are organised and such will also go on here...

**Comment by ZakGhouze** [comment]
Have sketched out site map... Need to scan in and annotate.

Goals? - need clarification. Function of each page?

**Comment by ZakGhouze** [comment]
Combine existing site plan layout (News/Blog, Intro, Background & Links, What / How / Who - Join Us, etc.) with categories of user / goals (TEAM, promoters, translators, developers, donors, users).

**Comment by ZakGhouze** [comment]
Add help page - lightweight instruction on what each icon does, etc. (Click the ? on anywhere within the app...)

NEEDS TO BE SIMPLE so as not to put people off... The aim is ease of use; anything complicated is a barrier to participation...

(*This is separate from more detailed user guide, which will expand on Sharing Groups...)

**Comment by vvorski** [comment]
Reviewed goals agreed these are ok for now.

**Comment by vvorski** [comment]
Zak will put into document.

**Comment by ZakGhouze** [comment]
Initial outline typed up... Shared as infosite site map here -:
https://docs.google.com/document/d/1V-JVWifZAv5Fekln3q6-L3s7-WynQTiT-H9SxTDeFSA/edit 

Lots more to add and incorporate...

**Comment by vvorski** [comment]
Moved to:

https://app.asana.com/0/10716696677062/10716696677182
