### ISSUE TITLE
Get domain for production version of Share❣

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#92]
Would be great to be able to get this.
http://share.it/

Need to try and contact them through the registrar, hosting company... anyway we can...

**Comment by vvorski** [comment]
Zak to send Victor list of FB/linkedin/etc. profiles to contact.

**Comment by ZakGhouze** [comment]
www.share.it currently registered, but not displaying content, merely default Parallels control panel.

Have shared whois details etc. via GoogleDocs (see  Domain Name Details https://docs.google.com/document/d/15IVXIkoGYfJnDjBqEYuUzqo-QgzLkWXdnWm4AqCS8EM/edit)

Have contacted apparent hosts ovh.co.uk, but no response.

Have emailed info@share.it, but no response yet.

Have found relevant owner / admin names -: 
- Ezio Vaccari & Bruno Vaccari; Via Colli della Farnesina 164, Roma, 00135 RM, Italy

Also found potential matches on LinkedIn; will forward to Victor to contact them.

**Comment by ZakGhouze** [comment]
Have emailed VV with relevant LinkedIn details...

**Comment by vvorski** [comment]
e-mailing back and forth with them. we'll see how it goes...

**Comment by Fxcornejo** [comment]
Hi! @vvorski  Just curious if you were able to contact the person.

**Comment by vvorski** [comment]
@Fxcornejo I was able to contact them but they were asking a lot of money from what I remember, why do you ask?

**Comment by Fxcornejo** [comment]
Thanks!! I was considering registering it but if they are asking money is
not worthy. Out of curiosity, how did you find their email?

**Comment by vvorski** [comment]
@Fxcornejo send me a private email at victor@vorski.com and will share what I know!
