### ISSUE TITLE
Feedback on landing page design 

### ISSUE THREAD

**Issue by konewa** [Vorski-Imagineering/share#95]
Gif version:
https://drive.google.com/a/hiddendata.co/folderview?id=0B01XthWybvS6RkNabm5WYnVFcVU&usp=sharing
jpg
https://drive.google.com/a/hiddendata.co/file/d/0B01XthWybvS6Qi04VGZjNWJPMzQ/edit?usp=sharing

**Comment by vvorski** [comment]
- "Language" - language selection should be as on gif not as on jpeg
- sample share - this will be a slider scrolling and showing multiple shares, right? 
- sample share : Can we potentially add an explanation below or above the share image? Say 3-4 lines of story below the share... 
- sample share - the text, names, etc. will also be localised through C3PO?
- current page indicator - maybe put less shadow on the not-current pages and make the current page icon a little bigger so it is clearer which page viewing currently

**Comment by vvorski** [comment]
- we discussed all pages should display a "go to top" icon to make it easy to escape from the middle, did we agree we would do that?
- will there be a way to see the menu after scrolling down the page? Perhaps we should have an icon to allow access to the menu? Maybe same as Share menu? Any other ideas? Or do you think we don't need it?

**Comment by vvorski** [comment]
globe thinking of something like this:

http://cdn.vectorstock.com/i/composite/21,73/globe-vector-132173.jpg

**Comment by vvorski** [comment]
or even like this...

http://image.shutterstock.com/display_pic_with_logo/718384/109032923/stock-vector-globe-vector-line-illustrator-eps-109032923.jpg

**Comment by vvorski** [comment]
design accepted at today's meeting.
