### ISSUE TITLE
Frequent list lists all friends, including ones which I have no shares with.

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#96]
I think frequent list should only list 10 people, and only people I have done share with. 

![screen shot 2014-01-19 at 19 56 25](https://f.cloud.github.com/assets/1789426/1949287/7da26ae4-80f8-11e3-9002-75532f1df6a1.png)

**Comment by vvorski** [comment]
And the people I have most shares with are not at the top...

**Comment by vvorski** [comment]
still same problem for me...
http://share-test.parseapp.com/#/share/1

**Comment by rafallo** [comment]
HTML5 app cache caches old files. Browser should refresh cache after launching application. And after that, second launch would provide working application.

Is it happening still? 
What browser are you using?

If chrome it should work because it is working for me.

**Comment by vvorski** [comment]
I have eleven people showing in "frequent". @konewa  from a usability point of view how many people do you think we should limit it to?

**Comment by konewa** [comment]
In my opinion we should limit this list to 10

**Comment by konewa** [comment]
@rafallo lets do it till the end of this week

**Comment by vvorski** [comment]
@rafallo  what is the status?

**Comment by rafallo** [comment]
fixed to 10.

**Comment by vvorski** [comment]
looks ok.
