### ISSUE TITLE
Friends list should not show people I don't have shares with

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#97]
(this might be duplicate) but should only list people I have shares with...

![screen shot 2014-01-19 at 20 03 03](https://f.cloud.github.com/assets/1789426/1949304/6537c336-80f9-11e3-9b06-f2c1fcef4860.png)

**Comment by vvorski** [comment]
still same problem for me...

**Comment by vvorski** [comment]
@konewa  can you please check the bugs after they are fixed? I think that should be our process.

**Comment by konewa** [comment]
works now
