### ISSUE TITLE
not able to access from firefox

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#98]
No matter what I do the screen comes up like this:

![screen shot 2014-01-19 at 20 15 55](https://f.cloud.github.com/assets/1789426/1949339/2b8234e4-80fb-11e3-9e7b-226ea96e73d1.png)

**Comment by vvorski** [comment]
Btw. I have seen that state in another situation also, I think maybe when the network connection is down?

**Comment by konewa** [comment]
@rafallo will take care of this till the end of the week

**Comment by vvorski** [comment]
not supporting firefox in this version, only chrome.

**Comment by rafallo** [comment]
Chrome works, so task should be moved to another version or closed.

**Comment by vvorski** [comment]
sorry meant to close it.
