### ISSUE TITLE
thick border on photo, thicker than on icon

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#99]
is this intentional? I think the photo could be a little bigger and the border a little thinner.

![screen shot 2014-01-19 at 20 52 27](https://f.cloud.github.com/assets/1789426/1949379/61a64ad8-8100-11e3-8ef0-08359dbdaf92.png)

**Comment by vvorski** [comment]
hmmm. still same for me. Do I need to do something to dump the cached CSS?

![screen shot 2014-01-22 at 11 51 14](https://f.cloud.github.com/assets/1789426/1970664/1dd28904-8310-11e3-9760-a6ebb72ba774.png)

http://share-test.parseapp.com/#/

**Comment by rafallo** [comment]
CSS is cached via HTML5 application cache. According to HTML5 Application Cache spec cache should be updated during user first visit after manifest file change. So, after cache update you should reload page and changes should be visible. 

I've add event listener which notify user that cache has been updated and you can reload page right now. But there is one huge "no" for it: to make offline mode work, Share is caching friends profile images and share images in HTML5 app cache, so when you add new new share with image, application will ask you for reloading next time. 
I will check if I can cache images not in app cache, but local storage.

**Comment by vvorski** [comment]
looks good now.
